package com.achinthas.infoflow

import android.app.Notification
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.drawable.BitmapDrawable
import android.graphics.drawable.Drawable
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import android.util.Log
import java.io.File
import java.io.FileOutputStream

class NotiListenerService : NotificationListenerService() {

    override fun onNotificationPosted(sbn: StatusBarNotification?) {
        super.onNotificationPosted(sbn)

        sbn ?: return

        val packageName = sbn.packageName
        val notificationKey = sbn.key
        val id = sbn.id
        val category = sbn.notification.category
        val postTime = sbn.postTime
//        val date = Date(sbn.postTime)
        val ongoing = sbn.notification.flags and Notification.FLAG_ONGOING_EVENT != 0
        val extras = sbn.notification.extras

        val title = extras.getString(Notification.EXTRA_TITLE)
        val text = extras.getCharSequence(Notification.EXTRA_TEXT)?.toString()
        val bigTitle = extras.getCharSequence(Notification.EXTRA_TITLE_BIG)?.toString()
        val bigText = extras.getCharSequence(Notification.EXTRA_BIG_TEXT)
        val subText = extras.getCharSequence(Notification.EXTRA_SUB_TEXT)



        // Ignore notifications generated by your own app
        if (packageName == applicationContext.packageName) return

        // Ignore nullable title notifications
        if(title.isNullOrBlank()){
            return
        }

        val appName = try {
            val applicationInfo = packageManager.getApplicationInfo(packageName, 0)
            packageManager.getApplicationLabel(applicationInfo).toString()
        } catch (e: Exception) {
            packageName
        }


        // Ignore notification are ongoing applications
        //  if(ongoing) return



        // Folder per package so files from different package
        val folder = File(getExternalFilesDir(null), "InfoFlow_$packageName")
        folder.mkdirs()

        //  app icons and images

        // 1. Get Application Icon (App Logo)
        ///   IMPORTANT
        /// commented app icon and large icon reason -  wasting image processing time and space
        // able to access this 2 in frontend using package name

        //        val appIconDrawable = try {
        //            packageManager.getApplicationIcon(packageName)
        //        } catch (e: Exception) {
        //            null
        //        }
        //        saveDrawable(appIconDrawable, folder, "app_icon_$packageName.png")

        // 2. Small icon (status bar monochrome icon)
        //        val smallIconDrawable = try {
        //            sbn.notification.smallIcon?.loadDrawable(this)
        //        } catch (e: Exception) {
        //            null
        //        }
        //        saveDrawable(smallIconDrawable, folder, "small_icon_$packageName.png")



        // 3. Large icon (avatar / thumbnail shown on the left of the notification)
        val largeIconDrawable = try {
            sbn.notification.getLargeIcon()?.loadDrawable(applicationContext)
        } catch (e: Exception) {
            null
        }
        val largeIconPath = saveDrawable(largeIconDrawable, folder, "large_icon_${id}_${postTime}.png")

        // 4. Big picture — classic Bitmap style (older API / most apps)
        // IMPORTANT -  Above Android 12+ (API level 31) some apps use  EXTRA_PICTURE_ICON instead but
        val bigPictureBitmap: Bitmap? = extras.getParcelable(Notification.EXTRA_PICTURE)
        val bigPicturePath = saveBitmap(bigPictureBitmap, folder, "big_picture_${id}_${postTime}.png") // direct


        Log.d("NotificationService",
            """
                -----------------------------
                Received Notification:
                Key         : ${sbn.key}
                ID          : ${sbn.id}
                Tag         : ${sbn.tag}
                Package     : ${sbn.packageName}
                Title       : $title
                bigTitle    : $bigTitle
                Text        : $text
                Posted Time : $postTime
                Channel ID  : ${sbn.notification.channelId}
                bigText : $bigText
                subText : $subText
           
                category : $category
                ongoing : $ongoing
                
                
                ----------------------------
            
                -----------------------------
                """.trimIndent()
        )
    }


    private fun saveDrawable(drawable: Drawable?, folder: File, filename: String) : String? {
        if (drawable == null) return null
        return saveBitmap(drawableToBitmap(drawable), folder, filename)
    }

    private fun saveBitmap(bitmap: Bitmap?, folder: File, filename: String) : String? {
        if (bitmap == null) return null
        return try {
            val file = File(folder, filename)
            FileOutputStream(file).use { out ->
                bitmap.compress(Bitmap.CompressFormat.JPEG, 100, out)
            }

            file.absolutePath

        } catch (e: Exception) {
            Log.w("NotificationService", "Failed to save $filename: ${e.message}")
            null

        }
    }

    fun drawableToBitmap(drawable: Drawable?): Bitmap? {
        if (drawable == null) return null

        // return underlying bitmap directly if already BitmapDrawable
        if (drawable is BitmapDrawable && drawable.bitmap != null) {
            return drawable.bitmap
        }

        val width = if (drawable.intrinsicWidth > 0) drawable.intrinsicWidth else 100
        val height = if (drawable.intrinsicHeight > 0) drawable.intrinsicHeight else 100
        val bmp = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        val canvas = Canvas(bmp)
        drawable.setBounds(0, 0, canvas.width, canvas.height)
        drawable.draw(canvas)
        return bmp

    }


//    override fun onBind(intent: Intent): IBinder? {
//        return super.onBind(intent)
//    }

    override fun onDestroy() {
        super.onDestroy()
    }
}